<?php
$graph = [
    'pos satpam' => ['bangunan kosong' => 43, 'tiang bendera' => 84, 'baliho' => 52],
    'bangunan kosong' => ['pertashop' => 50, 'pos satpam' => 43],
    'baliho' => ['pos satpam' => 52],
    'pertashop' => ['bangunan kosong' => 50],
    'tiang bendera' => ['gedung laboratorium terpadu' => 56, 'parkiran mahasiswa gedung laboratorium' => 60],
    'gedung laboratorium terpadu' => ['tiang bendera' => 56, 'bangunan dalam pembangunan' => 140, 'gedung kuliah c' => 220],
    'parkiran mahasiswa gedung laboratorium' => ['tiang bendera' => 60, 'saklar listrik' => 40],
    'gedung kuliah c' => ['gedung laboratorium terpadu' => 220, 'gedung kuliah d' => 10],
    'gedung kuliah d' => ['gedung kuliah c' => 10, 'kantin dekat study center' => 45],
    'bangunan dalam pembangunan' => ['kantin dekat study center' => 110, 'gedung laboratorium terpadu' => 70, 'perpustakaan kampus 2' => 70,'kantin dekat laboratorium' => 64],
    'perpustakaan kampus 2' => ['bangunan dalam pembangunan' => 70, 'study center kampus 2' => 110, 'gedung hijau terbengkalai' => 180],
    'study center kampus 2' => ['perpustakaan kampus 2' => 110],
    'kantin dekat study center' => ['gedung kuliah d' => 45, 'bangunan dalam pembangunan' => 110],
    'saklar listrik' => ['parkiran mahasiswa gedung laboratorium' => 40, 'parkiran mobil fakultas tarbiyah' => 27, 'fakultas tarbiyah dan ilmu keguruan' => 54],
    'parkiran mobil fakultas tarbiyah' => ['saklar listrik' => 27, 'kantin dekat laboratorium' => 61],
    'fakultas tarbiyah dan ilmu keguruan' => ['saklar listrik' => 54, 'gedung kuliah b' => 230],
    'gedung kuliah tarbiyah dan ilmu keguruan' => ['gedung kuliah b' => 84, 'gedung kuliah a' => 26, 'kantin terbengkalai' => 97,'kantin 4' => 7],
    'gedung kuliah b' => ['fakultas tarbiyah dan ilmu keguruan' => 230, 'gedung kuliah a' => 110, 'kantin dekat laboratorium' => 120,'kantin terbengkalai' => 120, 'gedung kuliah tarbiyah dan ilmu keguruan' => 84],
    'gedung kuliah a' => ['gedung kuliah tarbiyah dan ilmu keguruan' => 26, 'gedung kuliah b' => 110],
    'kantin dekat laboratorium' => ['bangunan dalam pembangunan' => 64, 'parkiran mobil fakultas tarbiyah' => 61, 'gedung kuliah b' => 120,'kantin terbengkalai' => 240],
    'kantin terbengkalai' => ['gedung hijau terbengkalai' => 5, 'gedung kuliah b' => 120, 'kantin dekat laboratorium' => 240,'gedung kuliah tarbiyah dan ilmu keguruan' => 97, 'kantin 1' => 51],
    'gedung hijau terbengkalai' => ['perpustakaan kampus 2' => 180, 'kantin terbengkalai' => 5, 'rumah 1' => 100],
    'kantin 4' => ['gedung kuliah tarbiyah dan ilmu keguruan' => 7, 'kantin 3' => 17],
    'kantin 3' => ['kantin 4' => 17, 'kantin 2' => 10],
    'kantin 2' => ['kantin 3' => 10, 'kantin 1' => 5],
    'kantin 1' => ['kantin 2' => 5, 'kantin terbengkalai' => 51],
    'rumah 1' => ['gedung hijau terbengkalai' => 100, 'rumah 2' => 17],
    'rumah 2' => ['rumah 1' => 17],
    
];
